# DATA
data_path: data/

# DATASETS

# MODELS
model_path: models/

# CHECKPOINTS
temp_checkpoint_path: temp_checkpoints/

# RESULTS
results_path: results/

# LOGGING
logging_path: logs/
logging_level: debug